export const data = {
    items: [
        { name: "聖光Esports同好会", type: "体験", classroom: "高3A", id: 63200, exhibitionId: 0 },
        { name: "高3英語劇", type: "劇・演技", classroom: "高3B", id: 62189, exhibitionId: 1 },
        { name: "生徒会展示", type: "体験", classroom: "高3C", id: 64082 , exhibitionId: 2 },
        { name: "ディズニー同好会", type: "体験", classroom: "高3D", id: 63207, exhibitionId: 3 },
        { name: "料理同好会", type: "食品", classroom: "高3E", id: 64021, exhibitionId: 4 },
        { name: "早撃ちジョニー", type: "体験", classroom: "高3F", id: 64082, exhibitionId: 5 },
        { name: "SeSDA", type: "食品", classroom: "高3ラウンジ", id: 65088, exhibitionId: 6 },
        // { name: '執行部景品', type: 'その他', classroom: '高校ゼミ室1', id: 0 },
        // { name: '保護者バザー', type: '販売', classroom: '中1A', id: 0 },
        { name: "生徒会展示", type: "体験", classroom: "中1B", id: 63042, exhibitionId: 7 },
        // { name: '受験相談', type: '体験', classroom: '中1C', id: 0 },
        { name: "昭和歌謡研究会", type: "鑑賞", classroom: "中1D", id: 64217, exhibitionId: 8 },
        // { name: '医療相談', type: '鑑賞', classroom: '', id: 0 },
        { name: "数学研究会", type: "体験", classroom: "中1E", id: 63221, exhibitionId: 9 },
        { name: "聖光道場", type: "体験", classroom: "中1UT", id: 63215 , exhibitionId: 10 },
        // { name: 'インターアクトクラブ（食品店舗）' ,type: '食品' ,classroom: '中1ラウンジ', id: 0},
        { name: "駅弁", type: "食品", classroom: "高2A", id: 65066, exhibitionId: 11 },
        { name: "ご当地研究会", type: "鑑賞", classroom: "高2B", id: 64226, exhibitionId: 12 },
        { name: "物理化学部", type: "体験", classroom: "高2C", id: 63123, exhibitionId: 13},
        { name: "地学天文部", type: "鑑賞", classroom: "高2D", id: 63138, exhibitionId: 14},
        { name: "ボードゲーム同好会", type: "体験", classroom: "高2E", id: 64173, exhibitionId: 15},
        { name: "ガンダム研究会", type: "鑑賞", classroom: "高2F", id: 63004, exhibitionId: 16},
        { name: "〜占いの館〜", type: "体験", classroom: "高2ラウンジ", id: 63227, exhibitionId: 17},
        { name: "ボールぽこぽこ", type: "体験", classroom: "吹き抜け", id: 63073, exhibitionId: 18},
        // 古本市に統合
        // { name: '古本市（ビブリオバトル）', type: '販売', classroom: '図書PC室', id: 0 },
        { name: "古本市", type: "販売", classroom: "図書室", id: 64154, exhibitionId: 19 },
        { name: "わたあめ", type: "食品", classroom: "中2A", id: 63021, exhibitionId: 20 },
        { name: "ぶいえいす", type: "体験", classroom: "中2B", id: 64151 , exhibitionId: 21 },
        { name: "Trick×Hark", type: "鑑賞", classroom: "中2C", id: 63142 , exhibitionId: 22 },
        { name: "Trick×Hark", type: "鑑賞", classroom: "中2D", id: 63142, exhibitionId: 23 },
        { name: "ぎゃんぶる。", type: "体験", classroom: "中2E", id: 64033, exhibitionId: 24 },
        // { name: '管理部門', type: '#N/A', classroom: '中2UT', id: 0 },
        { name: "聖光縁日", type: "体験", classroom: "中2ラウンジ", id: 63016, exhibitionId: 25 },
        { name: "コンピュータ部", type: "体験", classroom: "中教室1", id: 63017, exhibitionId: 26 },
        { name: "教室劇", type: "劇・演技", classroom: "中教室2", id: 64072, exhibitionId: 27 },
        // { name: 'ライブハウス', type: '企画', classroom: '音楽室2', id: 0 },
        // { name: 'オルガン', type: '企画', classroom: '聖堂', id: 0 },
        // { name: '聖書研究会', type: '鑑賞', classroom: '宗教準備室', id: 0 },
        { name: "交通研究部", type: "体験", classroom: "高1A", id: 63041, exhibitionId: 28 },
        { name: "交通研究部", type: "体験", classroom: "高1B", id: 63041, exhibitionId: 29},
        { name: "プロ野球研究会", type: "体験", classroom: "高1C", id: 64129, exhibitionId: 30},
        { name: "クイズ研究会", type: "体験", classroom: "高1D", id: 65036, exhibitionId: 31},
        { name: "SeSDA", type: "体験", classroom: "高1E", id: 64022, exhibitionId: 32},
        { name: "模型同好会", type: "鑑賞", classroom: "高1ラウンジ", id: 64005, exhibitionId: 33},
        { name: "生物部", type: "鑑賞", classroom: "生物実験室", id: 63055, exhibitionId: 34},
        { name: "地学天文部", type: "体験", classroom: "共通実験室", id: 63138, exhibitionId: 35},
        { name: "物理科学部", type: "体験", classroom: "物理実験室", id: 63123, exhibitionId: 36},
        { name: "ポケモンセンターSeiko", type: "鑑賞", classroom: "中3A", id: 63065, exhibitionId: 37},
        { name: "カードゲーム同好会", type: "体験", classroom: "中3B", id: 63190, exhibitionId: 38},
        { name: "音楽喫茶", type: "食品", classroom: "中3C", id: 63106, exhibitionId: 39},
        { name: "地理歴史巡見部", type: "鑑賞", classroom: "中3D", id: 63039, exhibitionId: 40},
        { name: "地理歴史巡見部", type: "鑑賞", classroom: "中3E", id: 63039, exhibitionId: 41},
        // { name: '手荷物預かり所', type: 'その他', classroom: '中3UT', id: 0 },
        { name: "ボカロDTM同好会", type: "鑑賞", classroom: "中3ラウンジ", id: 64007 },
        { name: "かるた会", type: "鑑賞", classroom: "和室", id: 64060 },
        { name: "エースをねらえ！", type: "体験", classroom: "屋上テニスコート", id: 63176, exhibitionId: 42 },
        { name: "魔女の卓球便", type: "体験", classroom: "第2体育館", id: 63059, exhibitionId: 43 },
        { name: "美術部展示", type: "鑑賞", classroom: "美術室", id: 64095, exhibitionId: 44 },
        // { name: '芸術講座', type: '鑑賞', classroom: '技術工作室', id: null },
        { name: "リアル野球盤", type: "体験", classroom: "グラウンド", id: 65049, exhibitionId: 45 },
        { name: "SeSDA", type: "体験", classroom: "グラウンド", id: 64022, exhibitionId: 46 },
        { name: "くれえぷ屋", type: "食品", classroom: "ピロティ", exhibitionId: 47 },
        { name: "聖光餃子", type: "食品", classroom: "ピロティ", exhibitionId: 48 },
        { name: "塩焼きそば", type: "食品", classroom: "ピロティ", exhibitionId: 49 },
        { name: "フランクフルト", type: "食品", classroom: "ピロティ", exhibitionId: 50 },
        { name: "焼き鳥", type: "食品", classroom: "ピロティ", exhibitionId: 51 },
        { name: "食券購入", type: "食品", classroom: "ピロティ", exhibitionId: 52 },
        { name: "ドリンク", type: "食品", classroom: "中庭", exhibitionId: 53 },
        { name: "食堂", type: "食品", classroom: "食堂", exhibitionId: 54 },
        { name: "お土産", type: "食品", classroom: "ポアトラホール前", exhibitionId: 55 },
        { name: "IAC Coffee Stand", type: "食品", classroom: "中1ラウンジ", exhibitionId: 56 },
    ],
};